using CacheClientLib = CacheClient;
using TestApp.Models;

namespace TestApp;

class Program
{
    static void Main()
    {
        Console.WriteLine("=== Cache Server Test Application ===");

        // Configuration
        string cacheServerHost = "localhost";
        int cacheServerPort = 5050;

        CacheClientLib.ICache cache =
            new CacheClientLib.CacheClient(
                new CacheClientLib.CacheClientOptions
                {
                    Host = cacheServerHost,
                    Port = cacheServerPort
                });

        cache.Initialize();

        bool exit = false;

        while (!exit)
        {
            ShowMenu();
            Console.Write("Select option: ");
            var choice = Console.ReadLine();

            try
            {
                switch (choice)
                {
                    case "1":
                        AddProduct(cache);
                        break;

                    case "2":
                        GetProduct(cache);
                        break;

                    case "3":
                        UpdateProduct(cache);
                        break;

                    case "4":
                        RemoveProduct(cache);
                        break;

                    case "5":
                        RunMultiThreadedTest(cache);
                        break;

                    case "0":
                        exit = true;
                        break;

                    default:
                        Console.WriteLine("Invalid choice.");
                        break;
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
            }

            Console.WriteLine();
        }

        cache.Dispose();
        Console.WriteLine("Cache client disposed. Exiting.");
    }

    static void ShowMenu()
    {
        Console.WriteLine("------------------------------------------------");
        Console.WriteLine("1. Add Product");
        Console.WriteLine("2. Get Product");
        Console.WriteLine("3. Update Product");
        Console.WriteLine("4. Remove Product");
        Console.WriteLine("5. Run Multi-threaded Test");
        Console.WriteLine("0. Exit");
        Console.WriteLine("------------------------------------------------");
    }

    static void AddProduct(CacheClientLib.ICache cache)
    {
        var product = new Product
        {
            Id = 1,
            Name = "Sample Product",
            Price = 99.99m,
            Description = "This is a sample product."
        };

        cache.Add("product:1", product);
        Console.WriteLine("Product added to cache.");
    }

    static void GetProduct(CacheClientLib.ICache cache)
    {
        var product = cache.Get("product:1") as Product;

        if (product != null)
        {
            Console.WriteLine("Retrieved Product:");
            Console.WriteLine($"ID: {product.Id}");
            Console.WriteLine($"Name: {product.Name}");
            Console.WriteLine($"Price: {product.Price}");
            Console.WriteLine($"Description: {product.Description}");
        }
        else
        {
            Console.WriteLine("Product not found in cache.");
        }
    }

    static void UpdateProduct(CacheClientLib.ICache cache)
    {
        var updatedProduct = new Product
        {
            Id = 1,
            Name = "Updated Product",
            Price = 149.99m,
            Description = "Updated description"
        };

        cache.Update("product:1", updatedProduct);
        Console.WriteLine("Product updated.");
    }

    static void RemoveProduct(CacheClientLib.ICache cache)
    {
        cache.Remove("product:1");
        Console.WriteLine("Product removed from cache.");
    }

    // -----------------------------
    // Multi-threaded Test
    // -----------------------------
    static void RunMultiThreadedTest(CacheClientLib.ICache cache)
    {
        Console.Write("Enter number of threads: ");
        if (!int.TryParse(Console.ReadLine(), out int threadCount))
        {
            Console.WriteLine("Invalid number.");
            return;
        }

        Console.WriteLine($"Running {threadCount} concurrent cache requests...");

        var threads = new List<Thread>();

        for (int i = 0; i < threadCount; i++)
        {
            int index = i;

            var thread = new Thread(() =>
            {
                string key = $"product:{index}";
                var product = new Product
                {
                    Id = index,
                    Name = $"Product {index}",
                    Price = 10 + index,
                    Description = $"Generated by thread {index}"
                };

                try
                {
                    cache.Add(key, product);
                    var retrieved = cache.Get(key) as Product;

                    Console.WriteLine(
                        retrieved != null
                            ? $"Thread {index}: OK"
                            : $"Thread {index}: FAILED");
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Thread {index}: {ex.Message}");
                }
            });

            threads.Add(thread);
            thread.Start();
        }

        threads.ForEach(t => t.Join());

        Console.WriteLine("Multi-threaded test completed.");
    }
}
